[env:esp32-s3-devkitc-1]
platform = espressif32@^6.5.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
build_flags = 
	-DCORE_DEBUG_LEVEL=3
lib_ldf_mode = deep

lib_deps = 
	Wire
	SPI
	adafruit/RTClib@^2.1.4
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.0.4

[env:firmware_unit_test]
platform = espressif32@^6.5.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
build_flags = 
	-DCORE_DEBUG_LEVEL=3
	-DENABLE_FAULT_INJECTION_TEST
	-DUNIT_TEST_BUILD
lib_ldf_mode = deep

lib_deps = 
	Wire
	SPI
	adafruit/RTClib@^2.1.4
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.0.4

